### ISSUE TITLE
Add new Employee Bug

### ISSUE THREAD

**Issue by VolodymyrHoshko** [AndriiTur/ManagerProject#13]
1 Add Button is not visible, but all fields are set
Steps to reproduce:
- run exe
- open tab Employees
- set Name "q"
- set Surname "q"
- set Salary "1"

2 Add Button is visible, but not all fields are set
Steps to reproduce:
- run exe
- open tab Employees
- set Salary "1"
- set Name "q"
- set Surname "q"
- clear Name value
- click Add Button

3 Check also tabs Customers and Projects for these bugs

**Comment by AndriiTur** [comment]
fixed a76d5e020724a5f7d36c3b5f1344f69ef139134a
