### ISSUE TITLE
FindEmployeeFromID related

### ISSUE THREAD

**Issue by VolodymyrHoshko** [AndriiTur/ManagerProject#17]
1
FindEmployeeFromID
->
ExistsEmployeeById

2
if (FindEmployeeFromID(CurentProject.Manager.Employees[i].EmployeeID) == false)
->
if (!FindEmployeeFromID(CurentProject.Manager.Employees[i].EmployeeID))

Avoid comparison of Boolean values

3
CurentProject.EmployeesID is list
use IndoxOf instead foreach

**Comment by AndriiTur** [comment]
fixed 330a0fb8840dc6c009306ca657b883f711f485cc
