### ISSUE TITLE
XmlNodeHelper extension, SetNodeAtribute, SetNodeAtributeI, GetNodeAtribute, GetNodeAtributeI

### ISSUE THREAD

**Issue by VolodymyrHoshko** [AndriiTur/ManagerProject#2]
- implement XmlNodeHelper.SetNodeAtribute
- implement XmlNodeHelper.SetNodeAtributeI
- Use in all places XmlNodeHelper.SetNodeAtribute, XmlNodeHelper.SetNodeAtributeI, XmlNodeHelper.GetNodeAtribute, XmlNodeHelper.GetNodeAtributeI

**Comment by AndriiTur** [comment]
841f7b5a67388af8320b359a269b1d2e93ddd9ae
sorry i do all in one commit

**Comment by VolodymyrHoshko** [comment]
XmlNodeHelper.SetNodeAttribute is not implemented

for esample:
if node xml is `<test id="2">`
after SetNodeAttribute(node, "id", "1", "1")
node xml should by `<test >`
but will be without any changes `<test id="2">`

**Comment by VolodymyrHoshko** [comment]
also 
> Use in all places XmlNodeHelper.SetNodeAtribute, XmlNodeHelper.SetNodeAtributeI, XmlNodeHelper.GetNodeAtribute, XmlNodeHelper.GetNodeAtributeI

not done because you do not use SetNodeAtributeI and GetNodeAtributeI for int values

3145edf4fd0e9e78dbfa745a81ea8e588b9fe554

**Comment by AndriiTur** [comment]
3145edf4fd0e9e78dbfa745a81ea8e588b9fe554

**Comment by VolodymyrHoshko** [comment]
XmlNodeHelper.cs 
```
 public static void SetNodeAttributeI(XmlNode node, string attributeName, int value, int defaultValue = 0)

{
-    SetNodeAttribute(node, attributeName, value.ToString());
+    int intValue;
+    if (int.TryParse(value.ToString(), out intValue))
+        SetNodeAttribute(node, attributeName, intValue.ToString());
+    else
+        defaultValue.ToString();
}
```

What is this? =)
Do not do anything on this Issue before meeting with me

**Comment by AndriiTur** [comment]
01d6e6cecb0939587c5e89f12c984ed72b0108b4
