### ISSUE TITLE
Bug: Employees.SaveToFile

### ISSUE THREAD

**Issue by VolodymyrHoshko** [AndriiTur/ManagerProject#6]
internal void SaveToFile(XmlNode employeesNode)
for example if employeesNode have child node with name "Employee"
but "this.Count == 0"
after our save should be "this.Count == employeesNode.ChildNodes.Count"

Also this bug exists in functions:
- Customers.SaveToFile
- Projects.SaveToFile

**Comment by AndriiTur** [comment]
841f7b5a67388af8320b359a269b1d2e93ddd9ae
