### ISSUE TITLE
Do not done in issue "Rename #4"

### ISSUE THREAD

**Issue by VolodymyrHoshko** [AndriiTur/ManagerProject#7]
Previous Issue: https://github.com/AndriiTur/ManagerProject/issues/4

Employee.Date_Of_Employment -> DateOfEmployment
and others like date_Of_Employment -> dateOfEmployment

examples:
public DateTime Date_Of_Employment { get; private set; }
public Employee(int emploeeID, string name, string surname, DateTime date_Of_Employment, double salary,Manager manager) : base(manager) 
this.dateOfEmploymentDataGridViewTextBoxColumn.DataPropertyName = "Date_Of_Employment";
this.dateOfEmploymentDataGridViewTextBoxColumn.HeaderText = "Date_Of_Employment";
DateTime date_Of_Employment = DateTime.Parse(EmployeeDateTimePicker.Value.ToString(DateFomat));

**Comment by AndriiTur** [comment]
841f7b5a67388af8320b359a269b1d2e93ddd9ae
