### ISSUE TITLE
Fix spell error

### ISSUE THREAD

**Issue by VolodymyrHoshko** [AndriiTur/ManagerProject#8]
Atribute -> Attribute

**Comment by AndriiTur** [comment]
841f7b5a67388af8320b359a269b1d2e93ddd9ae

**Comment by VolodymyrHoshko** [comment]
Not done, because I found "Atribute" in XmlNodeHelper.SetNodeAttribute

when found something for rename use "Current Project" option
http://my.jetscreenshot.com/25239/20170113-yeni-56kb.jpg

**Comment by AndriiTur** [comment]
83dc5da5923cdead2f336196d9a3935be32d5842
