### ISSUE TITLE
using GetNodeAttributeI

### ISSUE THREAD

**Issue by VolodymyrHoshko** [AndriiTur/ManagerProject#9]
int.Parse(XmlNodeHelper.GetNodeAttribute(node, Employee.XMLEmployeeAttributeID));
->
XmlNodeHelper.GetNodeAtributeI(node, Employee.XMLEmployeeAttributeID);

Check others

**Comment by AndriiTur** [comment]
fixed

**Comment by AndriiTur** [comment]
3145edf4fd0e9e78dbfa745a81ea8e588b9fe554
